# Python image 
FROM python:3.10-slim

# Set the working directory 
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install  packages specified in requirements.txt
RUN pip install --no-cache-dir --timeout=60 -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

# testing dependencies
RUN pip install --no-cache-dir --timeout=60 -i https://pypi.tuna.tsinghua.edu.cn/simple pytest

# Run tests
CMD ["pytest", "tests/test_app.py","--tb=short", "-q"] 