apiVersion: v1
kind: Service
metadata:
  name: meal-planner-service
spec:
  type: NodePort
  selector:
    app: meal-planner
  ports:
    - protocol: TCP
      port: 5000        # service port 
      targetPort: 5000  # Port inside the container
      nodePort: 30001   # Port exposed to Minikube(host machine)
